# .github/workflows/deploy-github-pages.yaml

# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
    release:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

# List of jobs
jobs:
    deploy:
        runs-on: ubuntu-latest
        # Job steps
        steps:
            # Manual Checkout
            - uses: actions/checkout@v4

            # Set up Node
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: npm install
                  build_command: npm build-storybook
                  path: storybook-static
                  checkout: false
